// <auto-generated />
using System;
using InterviewCopilot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterviewCopilot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewCopilot.Domain.Resumes.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Profile")
                        .HasColumnType("jsonb")
                        .HasColumnName("profile");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasDatabaseName("ux_resumes_one_current")
                        .HasFilter("is_current");

                    b.HasIndex("OwnerId", "CreatedAt");

                    b.ToTable("resumes", (string)null);
                });

            modelBuilder.Entity("InterviewCopilot.Domain.Resumes.Resume", b =>
                {
                    b.OwnsOne("InterviewCopilot.Domain.Common.AnalysisSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("ResumeId");

                            b1.HasKey("ResumeId");

                            b1.ToTable("resumes");

                            b1.ToJson("source");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");

                            b1.OwnsOne("InterviewCopilot.Domain.Common.BlobReference", "Blob", b2 =>
                                {
                                    b2.Property<Guid>("AnalysisSourceResumeId");

                                    b2.HasKey("AnalysisSourceResumeId");

                                    b2.ToTable("resumes");

                                    b2.WithOwner()
                                        .HasForeignKey("AnalysisSourceResumeId");
                                });

                            b1.Navigation("Blob");
                        });

                    b.Navigation("Source")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
